repos:
-   repo: https://github.com/python-poetry/poetry
    rev: '1.8.2'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
    -   id: poetry-install

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.0
    hooks:
    -   id: black
        language_version: python3.12
