repos:
-   repo: https://github.com/python-poetry/poetry
    rev: 1.8.2
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
    -   id: poetry-install

-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ['--profile', 'black', '--check-only', '--diff']
        files: ^(django_hierarchical_models|tests)/

-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: ['--extend-ignore=E203,E701', '--max-line-length=88']
        files: ^(django_hierarchical_models|tests)/

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.0
    hooks:
      - id: black
        language_version: python3.12
