repos:
-   repo: https://github.com/python-poetry/poetry
    rev: '1.8.2'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
    -   id: poetry-export
    -   id: poetry-install

#-   repo: https://github.com/tox-dev/tox
#    rev: 4.14.2
#    hooks:
#    -   id: tox
#        entry: tox
#        verbose: true
#        pass_filenames: false
