from django.test import TestCase

from tests.models import NSMTestModel


class NSMTests(TestCase):

    def assert_chunk(self, node: NSMTestModel, left: int, right: int):
        self.assertEqual(node._left, left, f"{node}._left != {left}")
        self.assertEqual(node._right, right, f"{node}._right != {right}")

    def test_child_from_right(self):
        n1 = NSMTestModel.objects.create(num=1)
        self.assert_chunk(n1, 0, 1)
        n2 = NSMTestModel.objects.create(num=2)
        self.assert_chunk(n1, 0, 1)
        self.assert_chunk(n2, 2, 3)
        n3 = NSMTestModel.objects.create(num=3)
        self.assert_chunk(n1, 0, 1)
        self.assert_chunk(n2, 2, 3)
        self.assert_chunk(n3, 4, 5)
        n3.set_parent(n2)
        n1.refresh_from_db()
        n2.refresh_from_db()
        n3.refresh_from_db()
        self.assert_chunk(n1, 0, 1)
        self.assert_chunk(n2, 2, 5)
        self.assert_chunk(n3, 3, 4)
        n2.set_parent(n1)
        n1.refresh_from_db()
        n2.refresh_from_db()
        n3.refresh_from_db()
        self.assert_chunk(n1, 0, 5)
        self.assert_chunk(n2, 1, 4)
        self.assert_chunk(n3, 2, 3)

    def test_child_from_left(self):
        n1 = NSMTestModel.objects.create(num=1)
        self.assert_chunk(n1, 0, 1)
        n2 = NSMTestModel.objects.create(num=2)
        self.assert_chunk(n1, 0, 1)
        self.assert_chunk(n2, 2, 3)
        n3 = NSMTestModel.objects.create(num=3)
        self.assert_chunk(n1, 0, 1)
        self.assert_chunk(n2, 2, 3)
        self.assert_chunk(n3, 4, 5)
        n1.set_parent(n2)
        n1.refresh_from_db()
        n2.refresh_from_db()
        n3.refresh_from_db()
        self.assert_chunk(n1, 1, 2)
        self.assert_chunk(n2, 0, 3)
        self.assert_chunk(n3, 4, 5)
        n2.set_parent(n3)
        n1.refresh_from_db()
        n2.refresh_from_db()
        n3.refresh_from_db()
        self.assert_chunk(n1, 2, 3)
        self.assert_chunk(n2, 1, 4)
        self.assert_chunk(n3, 0, 5)

    def test_consolidate(self):
        n1 = NSMTestModel.objects.create(num=1)
        n2 = NSMTestModel.objects.create(num=2)
        n3 = NSMTestModel.objects.create(num=3)
        n4 = NSMTestModel.objects.create(num=4)
        n5 = NSMTestModel.objects.create(num=5)
        n6 = NSMTestModel.objects.create(num=6)
        n7 = NSMTestModel.objects.create(num=7)
        self.assert_chunk(n1, 0, 1)
        self.assert_chunk(n2, 2, 3)
        self.assert_chunk(n3, 4, 5)
        self.assert_chunk(n4, 6, 7)
        self.assert_chunk(n5, 8, 9)
        self.assert_chunk(n6, 10, 11)
        self.assert_chunk(n7, 12, 13)
        n7.set_parent(n2)
        for node in (n1, n2, n3, n4, n5, n6, n7):
            node.refresh_from_db()
        self.assert_chunk(n1, 0, 1)
        self.assert_chunk(n2, 2, 5)
        self.assert_chunk(n3, 6, 7)
        self.assert_chunk(n4, 8, 9)
        self.assert_chunk(n5, 10, 11)
        self.assert_chunk(n6, 12, 13)
        self.assert_chunk(n7, 3, 4)
        n4.set_parent(n5)
        for node in (n1, n2, n3, n4, n5, n6, n7):
            node.refresh_from_db()
        self.assert_chunk(n1, 0, 1)
        self.assert_chunk(n2, 2, 5)
        self.assert_chunk(n3, 6, 7)
        self.assert_chunk(n4, 9, 10)
        self.assert_chunk(n5, 8, 11)
        self.assert_chunk(n6, 12, 13)
        self.assert_chunk(n7, 3, 4)
        n1.set_parent(n5)
        for node in (n1, n2, n3, n4, n5, n6, n7):
            node.refresh_from_db()
        self.assert_chunk(n1, 7, 8)
        self.assert_chunk(n2, 0, 3)
        self.assert_chunk(n3, 4, 5)
        self.assert_chunk(n4, 9, 10)
        self.assert_chunk(n5, 6, 11)
        self.assert_chunk(n6, 12, 13)
        self.assert_chunk(n7, 1, 2)
        n5.set_parent(n2)
        for node in (n1, n2, n3, n4, n5, n6, n7):
            node.refresh_from_db()
        self.assert_chunk(n1, 4, 5)
        self.assert_chunk(n2, 0, 9)
        self.assert_chunk(n3, 10, 11)
        self.assert_chunk(n4, 6, 7)
        self.assert_chunk(n5, 3, 8)
        self.assert_chunk(n6, 12, 13)
        self.assert_chunk(n7, 1, 2)
        n3.set_parent(n1)
        for node in (n1, n2, n3, n4, n5, n6, n7):
            node.refresh_from_db()
        self.assert_chunk(n1, 4, 7)
        self.assert_chunk(n2, 0, 11)
        self.assert_chunk(n3, 5, 6)
        self.assert_chunk(n4, 8, 9)
        self.assert_chunk(n5, 3, 10)
        self.assert_chunk(n6, 12, 13)
        self.assert_chunk(n7, 1, 2)
        n2.set_parent(n6)
        for node in (n1, n2, n3, n4, n5, n6, n7):
            node.refresh_from_db()
        self.assert_chunk(n1, 5, 8)
        self.assert_chunk(n2, 1, 12)
        self.assert_chunk(n3, 6, 7)
        self.assert_chunk(n4, 9, 10)
        self.assert_chunk(n5, 4, 11)
        self.assert_chunk(n6, 0, 13)
        self.assert_chunk(n7, 2, 3)
